899e9b89-316e-421d-9407-c54d97db78e8:
  '0000':
    '0000': 'Week 1: The Last Days - The Need of a Reformation'
    '0001': 'Week 2: The Everlasting Gospel - What Is It? - Its Power'
    '0002': 'Week 3: The Everlasting Gospel - Its Power, Object, Effect, and Duration'
    '0003': 'Week 4: The Fear, Glory, and Worship of God'
    '0004': 'Week 5: The Falling Away'
    '0005': 'Week 6: Babylon'
  '0001':
    '0000': 'Week 6: Babylon'
    '0001': "Week 7: The Beast\u2014What It Is"
    '0002': 'Week 8: The Protestant Reformation'
    '0003': 'Week 9: Babylon the Great'
    '0004': 'Week 10: An Image to the Beast'
  '0002':
    '0000': 'Week 10: An Image to the Beast'
    '0001': 'Week 11: The Image and Mark'
    '0002': 'Week 12: World-Wide Apostasy'
    '0003': 'Week 13: The Character and Triumph of God''s Remnant People'
  '0003':
    '0000': Front Matter - Sabbath School Quarterly, First Quarter 1896
    '0001': Back Matter - Sabbath School Quarterly, First Quarter 1896
