name: Build and Deploy Lessons Index

on:
  push:
    branches:
      - reproduced

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Run indexer script
        run: |
          python index_lessons.py
          echo "Lesson indexing completed"
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .       
          branch: gh-pages  
          clean: true    
          clean-exclude: |
            .git
            .github
          commit-message: "Update lessons index [skip ci]"